//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alcachofa.Properties.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alcachofa.Properties.Resource.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string about_menu {
            get {
                return ResourceManager.GetString("about_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Audio.
        /// </summary>
        internal static string audio_button {
            get {
                return ResourceManager.GetString("audio_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string audio_menu {
            get {
                return ResourceManager.GetString("audio_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better audio quality.
        /// </summary>
        internal static string better_audio_quality_menu {
            get {
                return ResourceManager.GetString("better_audio_quality_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for better audio queality.
        ///
        ///Warning: You can generate a waiting time that is too high for each audio file..
        /// </summary>
        internal static string better_audio_tool_tip {
            get {
                return ResourceManager.GetString("better_audio_tool_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel download.
        /// </summary>
        internal static string cancel_button {
            get {
                return ResourceManager.GetString("cancel_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close application.
        /// </summary>
        internal static string close_application {
            get {
                return ResourceManager.GetString("close_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer&apos;s Twitter.
        /// </summary>
        internal static string developers_twitter_menu {
            get {
                return ResourceManager.GetString("developers_twitter_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string english_language_menu {
            get {
                return ResourceManager.GetString("english_language_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit_menu {
            get {
                return ResourceManager.GetString("exit_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string file_menu {
            get {
                return ResourceManager.GetString("file_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string languages_menu {
            get {
                return ResourceManager.GetString("languages_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string ProgressBar {
            get {
                return ResourceManager.GetString("ProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save in....
        /// </summary>
        internal static string save_button {
            get {
                return ResourceManager.GetString("save_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save in....
        /// </summary>
        internal static string save_in_menu {
            get {
                return ResourceManager.GetString("save_in_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string spanish_language_menu {
            get {
                return ResourceManager.GetString("spanish_language_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Video.
        /// </summary>
        internal static string video_button {
            get {
                return ResourceManager.GetString("video_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube link : .
        /// </summary>
        internal static string youtube_link {
            get {
                return ResourceManager.GetString("youtube_link", resourceCulture);
            }
        }
    }
}
